### ISSUE TITLE
Problem with complex types

### ISSUE THREAD

**Issue by fhdk** [robisim74/angular2indexedDB#1]
I have been looking at your project and another named like yours but with a `dash`.

Your sample app is working as expected. When porting to use a more complex type I ran into issues.

Throwing errors about `Observable<string> not assignable to ...` It was most educating :+1: to figure this out. I finally solved the puzzle. When I removed the casted return type `Observable<string>` and `Observable<any>` from the  service API functioncalls those errors went away.

The result is placed here https://github.com/fhdk/ng2-idx-db-service

**Comment by robisim74** [comment]
Thanks for the reporting.

Greetings,

Roberto
